### PR TITLE
New changes

### PR DESCRIPTION
**Pull request by lfoppiano**
I've noticed that the latest commits were done on a detached head... 

I'm creating a PR in case we want to double-check

### CODE REVIEW

**Comment by lfoppiano** [comment]
@Aazhar could you please have a look?

**Comment by Aazhar** [comment]
Hi Luca,
Indeed these are the changes regarding char mapping to resolve some font mapping issues (for greek characters for instance) and some cleanup to generate only what is needed for pdfalto excluding stuff used to generate graphics (used by pdftopng, pdftojpeg...)

**Comment by Aazhar** [comment]
Actually the submodule reference from pdfalto needs to be fixed too (detached -> master ?)

**Review by Aazhar — APPROVED** [review]

**Comment by lfoppiano** [comment]
Thanks @Aazhar. Indee we will have to update the submodule but we will fix this after the release ;-)

**Pull request merged**
